# Generated by Django 4.2.11 on 2024-05-14 11:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('stage_id', models.CharField(max_length=255)),
                ('maintenance_type', models.CharField(max_length=255)),
                ('user_id', models.IntegerField(null=True)),
                ('priority', models.CharField(max_length=255)),
                ('equipment_id', models.IntegerField(null=True)),
                ('description', models.TextField()),
                ('instruction_text', models.TextField()),
                ('maintenance_team_id', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='managed_teams', to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MyTasks',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('tasks', models.ManyToManyField(related_name='mytasks', to='app.task')),
            ],
        ),
    ]
