# Generated by Django 4.2.11 on 2024-05-17 12:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='create_date',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
        ),
        migrations.AddField(
            model_name='task',
            name='schedule_date',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
        ),
    ]
