# Generated by Django 4.2.11 on 2024-05-17 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_task_create_date_task_schedule_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('maintenance_team_id', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='task',
            name='equipment_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.equipment'),
        ),
    ]
