# Generated by Django 4.2.11 on 2024-05-17 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_task_equipment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='equipment_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.equipment'),
        ),
    ]
